name: Create Client Sample Release

on:
  push:
    name: Push
  release:
    types: [created]
    name: Release

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Setup .NET Core SDK 6.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0

      - name: Install Server dependencies
        run: cd Server && dotnet nuget add source https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-net/nuget/v3/index.json && dotnet restore

      - name: Build Server
        run: cd Server && dotnet build --configuration Release --no-restore

      - name: Install Client dependencies
        run: cd Client && npm install

      - name: Build Client
        run: cd Client && npm run build

      - name: Package
        shell: bash
        run: |
          release_name=Calling-Tutorial
          unset CI
          # Copy to folder
          mkdir Client/dist/Server
          pwd
          ls
          ls Client/dist
          cp Server/bin/Release/net6.0/* Client/dist/Server
          cp Server/bin/Release/net6.0/web.config Client/dist/

          7z a -tzip -r "calling-tutorial-build.zip" Client/dist/*

          # Delete output directory
          rm -r "Client/dist"

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "calling-tutorial-build.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
